# -*- coding: utf-8 -*-
"""Data Science Capstone New.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iXh_jLxdt6ZwvGXbB798zOvvBbJHYBJM

# Climate Change Team — Combined Data Investigation Notebook
## Part A: Week 2 (Define) — Data Cleaning & Visualization
## Part B: Week 4 (Prototype) — Machine Learning & Model Comparison

**Dataset:** Our World in Data — CO2 and Greenhouse Gas Emissions

This notebook contains two work sessions from your Capstone Data Investigation, combined into a single file for easy reference:

- **Part A (Week 2, Wednesday):** Assess → Clean → Visualize → Tell the Story → HCD Design Sprint #2 (Problem Statement)
- **Part B (Week 4):** Define target → Feature engineering → Baseline → Multi-algorithm comparison → Fairness check → HCD Design Sprint #4 (Prototype)

**Run Part A first, top to bottom** — it produces the cleaned dataset and saved CSV that Part B depends on. Part B also includes a fallback that re-cleans from scratch if you skip straight to it, but running Part A first is strongly recommended so your cleaning decisions carry through consistently.

---

---
# PART A — Week 2, Day 3 (Wednesday): Data Cleaning & Visualization + HCD Design Sprint #2
---

# Week 2, Day 3 (Wednesday) — Climate Change Team
## Colab Lab: Data Cleaning & Visualization + HCD Design Sprint #2

**Dataset:** Our World in Data — CO2 and Greenhouse Gas Emissions
**HCD Phase:** Define — *"Name the problem precisely enough to act on it."*
**Today you will:** Assess → Clean → Visualize → Tell the Story → Write your team's Problem Statement

---

### Vocabulary you need before you start

| Term | Plain-English meaning |
|---|---|
| **Missing value** | A cell in the spreadsheet that is blank — the measurement was never collected, or doesn't apply. |
| **Outlier** | A data point far outside the normal range. Sometimes it's an error. Sometimes it's the most important data point in the whole dataset. |
| **Regional aggregate** | A row that isn't a real country — it's a *rollup* like "World," "Asia," or "European Union (27)." These will break a country-level analysis if you don't catch them. |
| **Data-ink ratio** | A design idea: every pixel of ink on a chart should carry information. Delete anything that doesn't. |
| **Finding-based title** | A chart title that states the *result*, not the *topic*. Not "CO2 by Country" — instead "China's per-person emissions have overtaken the EU's since 2005." |

> **Today's rule:** every time you drop a row, fill a blank, or pick a chart type, you must be able to say *why* in one sentence. "I felt like it" is not a justification. A data scientist's decisions are auditable.

### Warm-up discussion (no coding — 3 min)

Yesterday (Tuesday) we looked at charts that lied through design choices: truncated axes, misleading colors, cherry-picked time windows.

**Discuss with your team before you touch any code:**
1. Your dataset tracks CO2 emissions for every country since the 1700s-1800s. What's one way someone could cherry-pick this data to make a *false* claim about climate change (in either direction — overstating OR understating the problem)?
2. Who collected this data, and who might be undercounted or missing? (Hint: think about which countries have had reliable government statistics agencies for 150+ years, and which haven't.)

Write your answers in your Data Journal now — you'll need this thinking for your Data Empathy Map.

## Step 0 — Setup

Run the cell below to import your tools and load the dataset.

**Concept check:** `pandas` is the library that lets Python read and manipulate spreadsheet-like data (rows and columns). `matplotlib` and `seaborn` draw charts. We import them once, at the top, so every cell below can use them.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Make charts a readable size by default
plt.rcParams["figure.figsize"] = (9, 5)
sns.set_style("whitegrid")

# ---- LOAD THE DATASET ----
# Fallback below points to the official Our World in Data GitHub repo.
DATA_URL = "https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv"

df = pd.read_csv(DATA_URL)
print("Loaded!  Shape:", df.shape)
df.head()

"""## Step 1 — Assess: Write a Data Audit Report

Before you clean anything, you have to know what's broken. Run each cell below and **record what you find** in the Data Audit Report template at the bottom of this section.

**Function reminders:**
- `df.info()` → data types and which columns have missing values
- `df.describe()` → mean, min, max, etc. for every numeric column (a fast way to spot impossible values, like a negative population)
- `df.isnull().sum()` → exact count of missing values per column

"""

df.info()

df.describe()

missing_counts = df.isnull().sum().sort_values(ascending=False)
missing_pct = (missing_counts / len(df) * 100).round(1)
pd.DataFrame({"missing_count": missing_counts, "missing_pct": missing_pct}).head(20)

"""### Concept: "Regional aggregates" — the hidden trap in this dataset

This dataset does **not** contain only real countries. It also contains rollup rows like `"World"`, `"Asia"`, `"European Union (27)"`, and `"High-income countries"`. These are useful for some questions, but they will **wreck** a country-level comparison — imagine averaging "World" in with 190 actual countries.

**How do we tell them apart?** Real countries have a 3-letter `iso_code` (like `USA`, `IDN`, `DNK`). Regional aggregates almost always have a **blank/NaN** `iso_code`.

Run this cell to see the difference:

"""

# Rows with NO iso_code are regional aggregates, not real countries
aggregates = df[df["iso_code"].isnull()]
print("Number of aggregate rows:", len(aggregates))
print("\nExamples of aggregate 'country' names:")
print(aggregates["country"].unique()[:15])

"""> **Data Journal prompt (answer now):** If you left these aggregate rows in your analysis by accident, what specific number would be wrong, and who would be misled by it? Be specific — name a chart or statistic.

### Data Audit Report — fill in the blanks

> **Dataset shape:** 50,411 rows × 79 columns
>
> **Top 3 columns with the most missing data, and my guess for *why* each is missing:**
> 1. Column: `share_global_cumulative_other_co2` — % missing: 95.7% — Why: this is a niche breakdown (CO2 from non-fuel/non-cement "other" industrial sources) that most national statistical agencies never separately report.
> 2. Column: `share_global_other_co2` — % missing: 95.7% — Why: same underlying "other CO2" source category, missing for the same reporting-gap reason.
> 3. Column: `other_co2_per_capita` — % missing: 94.7% — Why: a per-capita version of the same rarely-tracked source, so it inherits the same gap plus needs population data to compute.
>
> **Number of regional-aggregate rows found:** 7,931 rows (36 distinct aggregate labels, e.g. `World`, `Africa`, `Asia`, `European Union (27)`, `High-income countries`, `International shipping`).

## Step 2 — Clean: Build a documented, justified pipeline

**The ethics of cleaning, reminder from Monday:** every cleaning choice is an analytical choice. If you drop every row missing `co2`, are you dropping small poor countries at a higher rate than large rich ones? That would bias your final findings toward the countries that have always had reliable data. **Say so if it's true.**

We will build the pipeline in five small, checkable steps. Each step has a **baseline version that runs out of the box** — your job is to read it, understand it, then **tweak the choices** (which columns, which threshold, which fill strategy) to fit what your team actually needs for your Capstone question.

### Step 2a — Narrow to the columns your team actually needs

Working with all 79 columns is overwhelming and mostly irrelevant to your investigation. Baseline below keeps a working set of climate-relevant columns.

**Hint ladder (use only what you need):**
- *Nudge:* Look at the column list you saw in `df.info()`. Which ones relate to your team's research question?
- *Syntax:* `df[["col1", "col2", ...]]` selects a subset of columns.
- *Bridge:* If you want to *add* a column to the baseline list, just add its exact name (copy-paste from `df.info()` to avoid typos) into the list below.
"""

# BASELINE column set — tweak this list for your team's specific question
core_cols = [
    "country", "year", "iso_code", "population", "gdp",
    "co2", "co2_per_capita", "co2_growth_prct",
    "coal_co2", "oil_co2", "gas_co2", "cement_co2",
    "primary_energy_consumption", "energy_per_capita",
    "methane", "nitrous_oxide", "total_ghg",
    "temperature_change_from_co2", "temperature_change_from_ghg",
]

df_climate = df[core_cols].copy()
print("New shape:", df_climate.shape)
df_climate.head()

"""**Our justification:** We are removing rows with no `iso_code` because our research question is about comparing real countries, and mixing in continent/world rollups would double-count emissions and distort our averages. **One honest limitation of this baseline filter:** Kosovo is a real country but also has no `iso_code` in this dataset, so this simple rule drops it along with the actual aggregates. We're accepting that trade-off here for a cleaner baseline pipeline, but it's worth noting Kosovo is systematically excluded from every result below.

### Step 2b — Remove regional aggregates

**Justification (write this in a markdown cell of your own before moving on):** *"We are removing rows with no `iso_code` because our research question is about comparing real countries, and mixing in continent/world rollups would double-count emissions and distort our averages."*
"""

before = len(df_climate)
df_climate = df_climate[df_climate["iso_code"].notnull()].copy()
after = len(df_climate)
print(f"Removed {before - after} regional-aggregate rows. Remaining: {after}")

"""### Step 2c — Handle missing values

You have choices here, and they are NOT equivalent:
- `.dropna(subset=[...])` — deletes any row missing a value in the listed columns. Use when the column is essential and can't be reasonably estimated.
- `.fillna(0)` — replaces missing with zero. **Dangerous** — only correct if "missing" truly means "zero," e.g. a country that plausibly produced no cement.
- `.fillna(df[col].median())` — replaces missing with the typical value. Reduces bias from outliers, but hides the fact that data was missing at all.

**Baseline strategy below.** Your job: change ONE of these choices for a column central to your research question, and write a one-sentence justification for the change.

"""

# BASELINE strategy — tweak per the instructions above
# 1) co2 and co2_per_capita are central to almost every climate question -> drop rows missing them
df_climate = df_climate.dropna(subset=["co2", "co2_per_capita"]).copy()

# 2) gdp and population have lots of legitimate historical gaps -> leave as NaN for now (don't fake a number)
#    (We will exclude rows with missing gdp/population LATER, only in the specific analysis that needs them.)

# 3) Emissions-source breakdowns (coal/oil/gas/cement) -> fill missing with 0
#    Justification: for many small countries, "no data reported" for e.g. cement_co2 usually means
#    that source is negligible/near-zero for that country, not that the value is unknowable.
source_cols = ["coal_co2", "oil_co2", "gas_co2", "cement_co2"]
df_climate[source_cols] = df_climate[source_cols].fillna(0)

print("Shape after handling missing values:", df_climate.shape)
df_climate.isnull().sum()

"""**Our tweak + justification:** Instead of leaving `gdp` as NaN for missing rows (the baseline choice), we considered `.fillna(df["gdp"].median())` for `gdp` specifically -- but we rejected it, because GDP varies by orders of magnitude between countries (a small island nation and the US are not "close to the median"), so imputing a single global median would introduce a large, misleading distortion into a variable central to our wealth-vs-emissions question. We kept the baseline `dropna`-when-needed / leave-as-NaN-otherwise strategy for `gdp` and only drop those rows in the specific charts/models that require `gdp_per_capita`.

### Step 2d — Check for duplicates

**Function hint:** `df.duplicated(subset=["country", "year"])` flags rows that repeat the same country-year combination — which shouldn't happen in this dataset (one row per country per year).
"""

dupes = df_climate.duplicated(subset=["country", "year"]).sum()
print("Duplicate country-year rows found:", dupes)
# If dupes > 0, uncomment the line below to drop them, keeping the first occurrence:
# df_climate = df_climate.drop_duplicates(subset=["country", "year"], keep="first")

"""### Step 2e — Verify your cleaning worked

**Do not skip this.** An `assert` statement stops your notebook with an error if something you expect to be true is actually false — this is how professional data scientists catch mistakes before they become published errors.

"""

assert df_climate["co2"].isnull().sum() == 0, "co2 still has missing values!"
assert df_climate["co2_per_capita"].isnull().sum() == 0, "co2_per_capita still has missing values!"
assert df_climate["iso_code"].isnull().sum() == 0, "Regional aggregates are still in the data!"
print("All checks passed. Cleaned shape:", df_climate.shape)
df_climate.describe()

"""### Data Limitations paragraph -- Fill in

> **What our cleaning process couldn’t fix:** While our cleaning process identified mislabeled aggregate observations and imputed defensible zero values where missing data on sources of emissions exist, gaps in the measurement period can’t be fixed – entire decades are missing for countries without advanced statistical bureaus (particularly before 1950s), and `gdp` remains unobserved for about one-third of country-year periods even after the cleaning. Small and poorer countries are significantly underrepresented in our cleaned database compared to their true representation in the world, not because they don’t emit much but simply because they weren’t measured. Also, using the .fillna(0) approach for coal_co2/oil_co2/gas_co2/cement_co2 is implicitly assuming that “no report” equals “nothing”, which is quite a valid assumption for most small countries but could be incorrect for some other countries where the problem is not in nonexistence of emissions but in absence of measuring apparatus.

"""

# Save your cleaned dataset with a clear filename convention, per the syllabus.
from datetime import date
today_str = date.today().strftime("%Y%m%d")
out_name = f"climate_cleaned_{today_str}.csv"
df_climate.to_csv(out_name, index=False)
print("Saved:", out_name, "— now upload this to your GitHub repo.")

"""## Data Cleaning — Deep Dive: 5 Key Variables

Here's exactly what we did to each of the 5 variables most central to this investigation, and why.

| # | Variable | What it measures | Cleaning decision | Why |
|---|----------|-------------------|--------------------|-----|
| 1 | `co2` | Total annual CO2 emissions (million tonnes) | Dropped rows where missing (`dropna`) | Central outcome variable — an estimated or imputed value here would be fabricating the exact thing we're trying to measure. |
| 2 | `co2_per_capita` | CO2 emissions per person (tonnes/person/year) | Dropped rows where missing (`dropna`) | Our primary investigation variable (see Problem Statement) — same reasoning as `co2`. |
| 3 | `population` | Country population (people) | Left as-is; only excluded row-by-row in analyses that need it | Population is well-reported for almost all real countries in modern years, so it needed little intervention once aggregate rows were removed. |
| 4 | `gdp` | Gross domestic product (international-$) | Left as `NaN` where missing, never imputed | GDP has real, legitimate historical gaps (many countries lack pre-1950 GDP estimates, and OWID's `gdp` column stops being updated after 2022). Imputing it would fabricate economic history we don't have. |
| 5 | `coal_co2` / `oil_co2` / `gas_co2` / `cement_co2` (source breakdown) | CO2 by fuel/industrial source (million tonnes) | Filled missing values with `0` | For most small countries, "not reported" for a specific fuel source realistically means that source is negligible or absent — a defensible use of `fillna(0)`, unlike doing the same for `co2` itself. |

"""

# Quick numeric check on the 5 key cleaning variables
cleaning_vars = ["co2", "co2_per_capita", "population", "gdp", "coal_co2"]
df_climate[cleaning_vars].describe()

"""## Data Analysis — Deep Dive: 5 Key Variables

Beyond just cleaning, we ran descriptive statistics and correlations on 5 core variables to understand how they relate before building any chart or model.

"""

# Data Analysis: descriptive stats + correlation matrix for 5 key variables
analysis_vars = ["co2", "co2_per_capita", "gdp", "population", "total_ghg"]

print(df_climate[analysis_vars].describe())
print()
print("Correlation matrix:")
print(df_climate[analysis_vars].corr(numeric_only=True).round(3))

"""### Statistical Significance Check: Is the GDP <-> Emissions Relationship Real, or Just Noise?

A correlation coefficient alone doesn't tell you whether a relationship is statistically meaningful or could plausibly have arisen by chance in a sample this size. We test this with a **Pearson correlation significance test**, which gives us a p-value: the probability of seeing a correlation this strong (or stronger) if there were actually *no* real relationship between the two variables.

"""

from scipy import stats

# Is the GDP-per-capita <-> CO2-per-capita relationship statistically significant?
sig_check = df_climate[df_climate["year"] == 2022].copy()
sig_check["gdp_per_capita"] = sig_check["gdp"] / sig_check["population"]
sig_check = sig_check.dropna(subset=["gdp_per_capita", "co2_per_capita"])

r, p_value = stats.pearsonr(sig_check["gdp_per_capita"], sig_check["co2_per_capita"])
print(f"Pearson r = {r:.3f}")
print(f"p-value = {p_value:.2e}")
print(f"n = {len(sig_check)} countries")

alpha = 0.05
if p_value < alpha:
    print(f"\nSince p < {alpha}, we reject the null hypothesis of no correlation --")
    print("the relationship between GDP per capita and CO2 per capita is statistically significant.")
else:
    print(f"\nSince p >= {alpha}, we fail to reject the null hypothesis --")
    print("we cannot conclude there's a real relationship at the 95% confidence level.")

"""**Result:** r = 0.745, p ≈ 2.4 × 10⁻³⁰ (N = 164 nations). The p-value in question is mind-bogglingly lower than the conventional level of significance 0.05, thus the conclusion follows that the GDP/emissions connection in our sample is valid and not coincidental in statistical terms – even though statistical significance proves the existence of the connection beyond doubt rather than its strength or practical importance (the effect size is r = 0.745).

**What the numbers show, variable by variable:**

1. **`co2`** (total emissions) — Heavily right-skewed: mean (78.5 Mt) is far above the median (2.9 Mt), confirming a small number of huge emitters dominate the total.
2. **`co2_per_capita`** — Correlates only weakly with total `co2` (r ≈ 0.07) and with `population` (r ≈ -0.01). This is an important analytical finding on its own: **being a big total emitter and being a high per-person emitter are almost unrelated.**
3. **`gdp`** — Strongly correlated with `co2` (r ≈ 0.92) and `total_ghg` (r ≈ 0.88). Richer countries, in raw dollar terms, tend to be bigger total emitters — largely because richer countries also tend to be larger economies with more industry, not necessarily "dirtier" per person.
4. **`population`** — Correlates moderately with `co2` (r ≈ 0.63) but is essentially uncorrelated with `co2_per_capita` (r ≈ -0.01), reinforcing point 2: a country's headcount doesn't predict how much each resident emits.
5. **`total_ghg`** — Nearly perfectly correlated with `co2` (r ≈ 0.95), which makes sense since CO2 is the largest component of total greenhouse gases for most countries; it's not an independent signal so much as a broader version of the same measurement.

## Step 3 — Visualize: Four publication-quality charts

**Rule from yesterday:** every chart needs (1) a **finding-based title** — stating the result, not the topic — (2) labeled axes with units, and (3) a 2-sentence written interpretation. A chart with no interpretation is just decoration.

You will build one of each: **histogram, bar chart, line chart, scatter plot.** For each, read the concept, run the baseline, then tweak it.

### Chart 1 — Histogram: What does the distribution of per-person emissions look like?

**Concept:** A histogram groups a continuous number (here, `co2_per_capita`) into bins and counts how many rows fall in each bin. It answers: *is this measurement typical for most countries, or do a few extreme countries dominate?*

**Function hint:** `sns.histplot(data=df, x="column_name", bins=30)`

**What to look for:** Is the shape symmetric, or does it have a long tail (skewed)? A long right tail means a few countries emit *far* more per person than everyone else.
"""

# Use the MOST RECENT year available so the comparison is fair (not mixing 1850 with 2020)
latest_year = df_climate["year"].max()
df_latest = df_climate[df_climate["year"] == latest_year]

# BASELINE
plt.figure()
sns.histplot(data=df_latest, x="co2_per_capita", bins=30)
plt.xlabel("CO2 emissions per person (tonnes)")
plt.ylabel("Number of countries")
plt.title(f"Most Countries Emit Under 6 Tonnes Per Person in {latest_year} (Median = 3.2t)")
plt.show()

# HINT LADDER if you want to improve this chart:
#  Nudge: is bins=30 too coarse or too fine to see the shape clearly? Try a few values.
#  Syntax: change the number inside bins=... and re-run.
#  Bridge: try df_latest["co2_per_capita"] < 30  to filter out extreme outliers and re-plot,
#          so the "typical" countries are easier to see. Decide: should you keep or remove
#          those outlier countries? Justify your choice in the interpretation below.

"""> **Interpretation (2 sentences, with a real statistic and units):** In 2024, the median country emitted about **3.2 tonnes of CO2 per person**, and most countries fall well under 6 tonnes/person -- but Qatar sits far out on the right tail at **41.3 tonnes/person**, roughly 13x the median. We kept the outlier countries in the chart rather than filtering them out, since they're a real and important part of the story: a handful of oil-and-gas economies pull the "average" far above what's typical for most of the world.

### Chart 2 — Bar chart: Which countries/regions stand out for total emissions?

**Concept:** A bar chart compares a number across categories (here, countries). Use it for comparison, not for a continuous trend over time.

**Function hint:** `sns.barplot(data=..., x="co2", y="country", order=...)` — use `order=` to sort bars biggest-to-smallest so the finding is instantly visible. Use **horizontal** bars (`y="country"`) because country names are long.
"""

# BASELINE — top 10 emitting countries in the latest year, by TOTAL co2 (not per-capita)
top10 = df_latest.nlargest(10, "co2")

plt.figure()
sns.barplot(data=top10, x="co2", y="country",
            order=top10.sort_values("co2", ascending=False)["country"])
plt.xlabel("Total CO2 emissions (million tonnes)")
plt.ylabel("")
plt.title(f"Just 2 Countries Account for Over 70% of Top-10 {latest_year} Emissions")
plt.show()

# HINT LADDER:
#  Nudge: total emissions favor big/populous countries. Is that the fairest comparison for YOUR question?
#  Syntax: swap x="co2" for x="co2_per_capita" and re-run nlargest on that column instead.
#  Bridge: does the ranking change a lot between total vs per-capita? That difference IS a finding --
#          write about it.

"""> **Interpretation :** China (12,289 million tonnes) and the US (4,904 million tonnes) make up more than 70% of the total emissions from the top 10 countries in 2024. The ranking above is totally different from the per capita ranking presented as a histogram above. China is the #1 country for total emissions but somewhere in the middle of the per capita distribution, proving that "largest emitter" and "most per person" are truly distinct measures.

### Chart 3 — Line chart: How has something changed over time?

**Concept:** A line chart is for a **truly continuous time series** — use it only when the x-axis is time.

**Function hint:** `sns.lineplot(data=..., x="year", y="co2_per_capita", hue="country")`
"""

# BASELINE — pick a few countries to compare over the full time range
countries_to_compare = ["United States", "China", "India", "Nigeria"]  # <-- TWEAK this list for your team
df_trend = df_climate[df_climate["country"].isin(countries_to_compare)]

plt.figure()
sns.lineplot(data=df_trend, x="year", y="co2_per_capita", hue="country")
plt.xlabel("Year")
plt.ylabel("CO2 emissions per person (tonnes)")
plt.title("US Per-Capita Emissions Have Fallen Since 2005 While China's Rose")
plt.legend(title="Country")
plt.show()

# HINT LADDER:
#  Nudge: are you comparing countries with very different population sizes? Per-capita already
#         adjusts for that -- is that the right choice for this specific comparison?
#  Syntax: to zoom into a recent period only, filter first: df_trend[df_trend["year"] >= 1990]
#  Bridge: which country's LINE SHAPE tells the most surprising story? Zoom into just that one
#          country's trend using a second small plot.

"""> Explanation Per-capital CO2 emissions in the United States decreased from approximately **20.7 tonnes/person in 2005 to 14.2 tonnes/person** in the most recent year, a real decrease, while those in China increased from **4.5 to 8.7 tonnes/person** in the same time span. This is not happening because China’s levels have reached a certain point set by the United States, but rather due to the changing nature of energy in each country.

### Chart 4 — Scatter plot: Does wealth relate to emissions?

**Concept:** A scatter plot shows the relationship between two continuous variables — each dot is one country. This is the chart type we'll build on heavily in Week 3 (correlation/regression).

**Requirement:** at least one of your four charts must **challenge an assumption a reader might bring to the topic.** This is a strong candidate — many people assume "richer = always more emissions," but per-capita relationships are more nuanced.

**Function hint:** `sns.scatterplot(data=..., x="gdp_per_capita", y="co2_per_capita")`
"""

# gdp_per_capita isn't a column yet -- we have to CREATE it. This is a normal, expected step.
# NOTE: `gdp` stops being reported after 2022 in this dataset, so we use 2022 (the most recent
# year with real GDP coverage) for this chart instead of the absolute latest year.
gdp_year = 2022
df_gdp_year = df_climate[df_climate["year"] == gdp_year].copy()
df_gdp_year["gdp_per_capita"] = df_gdp_year["gdp"] / df_gdp_year["population"]

# Drop rows where we can't compute this (missing gdp or population) -- ONLY for this specific chart
df_scatter = df_gdp_year.dropna(subset=["gdp_per_capita", "co2_per_capita"])

plt.figure()
sns.scatterplot(data=df_scatter, x="gdp_per_capita", y="co2_per_capita", alpha=0.6)
plt.xscale("log")
plt.xlabel("GDP per person (US dollars, log scale)")
plt.ylabel("CO2 emissions per person (tonnes)")
plt.title(f"Wealth Predicts Emissions in {gdp_year} -- But Oil-Rich Nations Break the Pattern")
for c in ["Qatar", "Luxembourg"]:
    row = df_scatter[df_scatter["country"] == c]
    if len(row):
        plt.annotate(c, (row["gdp_per_capita"].values[0], row["co2_per_capita"].values[0]))
plt.show()

# HINT LADDER if you want to improve this chart:
#  Nudge: is the cloud of dots too squeezed on the left? Money often needs a LOG scale to see clearly.
#  Syntax: plt.xscale("log")   <- add this line before plt.show() and re-run
#  Bridge: which countries are the clearest EXCEPTIONS to the overall pattern (high GDP, low emissions
#          per person, or the reverse)? Label 2-3 of them using plt.annotate() and discuss why they
#          might be exceptions in your interpretation.

"""Interpretation : Indeed, there is a strong positive correlation between GDP per capita and CO2 per capita (correlation r ≈ 0.75). However, this graph challenges the assumption that income alone determines emissions, since Qatar, with a GDP per capita of $131,991, produces 37.9 tons of CO2 per person, while Switzerland, with a similar GDP per capita of $63,623, produces only 3.7 tons of CO2 per person."""



"""### Statistical Significance Check: Do High-Income and Low-Income Countries Really Emit Differently?

We also test this with a two-group comparison: split countries into "High income" and "Low income" halves (by median `gdp_per_capita`), then run an **independent two-sample t-test** on `co2_per_capita` to check whether the difference in group means is statistically significant or could be due to random sampling variation.

"""

# Split into two income groups at the median, then t-test their co2_per_capita
median_gdp_pc = sig_check["gdp_per_capita"].median()
sig_check["income_group"] = np.where(sig_check["gdp_per_capita"] >= median_gdp_pc, "High", "Low")

high_group = sig_check[sig_check["income_group"] == "High"]["co2_per_capita"]
low_group = sig_check[sig_check["income_group"] == "Low"]["co2_per_capita"]

t_stat, p_value2 = stats.ttest_ind(high_group, low_group, equal_var=False)  # Welch's t-test (unequal variances)

print(f"High-income group: n={len(high_group)}, mean co2_per_capita={high_group.mean():.2f} tonnes/person")
print(f"Low-income group:  n={len(low_group)}, mean co2_per_capita={low_group.mean():.2f} tonnes/person")
print(f"\nt-statistic = {t_stat:.3f}")
print(f"p-value = {p_value2:.2e}")

if p_value2 < 0.05:
    print("\np < 0.05 -- the difference in per-capita emissions between high- and low-income")
    print("countries is statistically significant, not just noise.")
else:
    print("\np >= 0.05 -- we cannot conclude the groups differ significantly.")

"""**Conclusion:** The mean value of emissions for high-income countries is 7.75 tonnes/person compared to the low-income countries which emit 1.30 tonnes/person (t ≈ 9.08, p ≈ 2.8 × 10⁻¹⁴, n = 82). This is a very significant difference and thus the division between income and emission values observed from the scatter plot above is actually a statistically significant trend in this data set.

## Data Visualization — Deep Dive: 3 Key Variables

Across our 4 required charts, we visualized **3 distinct variables**, each chosen because it answers a different piece of our investigation:

1. **`co2_per_capita`** (Chart 1: histogram, Chart 3: line) — our primary "who's responsible per person" measure, shown both as a snapshot distribution and as a trend over time.
2. **`co2`** (Chart 2: bar) — total national emissions, shown to make the "biggest emitter ≠ highest per-person emitter" contrast visible against Chart 1.
3. **`gdp_per_capita`** (Chart 4: scatter, engineered from `gdp` ÷ `population`) — used to test whether wealth explains the pattern we see in `co2_per_capita`.

## Step 4 — Story: Write a 150-word Data Brief

**Audience:** a city council member who has never seen your raw data and does not know what "per capita" means unless you explain it in context.

**Requirements:**
- 150 words, no more
- Your 3 most important findings, in plain language
- At least 2 specific statistics with units
- No jargon left unexplained (if you must use a term like "per capita," define it in the same sentence)
- End with what this means for a real decision

Draft it in the cell below (as a markdown cell, not code) or directly in your team doc.

### Your Data Brief (150 words):

However, not all nations are responsible for climate pollution in equal proportions. In terms of the total volume of emissions, the two biggest contributors are China and the US, contributing over 70% of emissions among the ten countries with the highest emission rates, where the emissions from China reach 12,289 million tonnes of CO2 in 2024. Still, taking into account the number of people living in particular nations reveals another picture. On average, per capita emissions or emissions from one citizen make 3.2 tonnes per year, whereas in Qatar, per capita emissions reach 41 tonnes. It is clear from these figures that the size of the population cannot be the only variable influencing emissions. Although wealth influences the volume of pollution, energy resources and industries also play a great role. The example of Qatar and Switzerland shows that even having different economic systems, Qatar still pollutes the atmosphere significantly more per person than Switzerland does.

## HCD Design Sprint #2 — Define: Write Your Team's Data Problem Statement

This is a **team** deliverable, reviewed and approved by your instructor before Thursday. Fill in every blank — vague blanks will be sent back for revision.

> **Our investigation asks:** Which countries bear the greatest responsibility for global CO2 emissions today, and does that responsibility track more closely with national wealth, population size, or something else?
>
> **The dataset we are using is:** the Our World in Data CO2 and Greenhouse Gas Emissions dataset, updated through 2024, with one row per country per year.
>
> **The key variable we are analyzing is:** `co2_per_capita` — CO2 emissions per person, measured in tonnes per person per year, ranging from near 0 to over 41 tonnes/person in our cleaned data.
>
> **Our investigation matters because:** climate policy and funding decisions are often based on *which* countries look like the biggest problem — without better understanding of the difference between total and per-person responsibility, lower-population high-per-capita emitters (and fast-industrializing lower-income countries) will continue to face mismatched scrutiny or support.
>
> **We define a meaningful finding as:** a pattern that holds across both the 10 most populous countries and the 10 highest-GDP countries, rather than being driven by one or two outliers (e.g., Qatar alone).

---

**Before you move on, check:** Does your question actually match a column that exists in `df_climate`? If not, revise the question now — don't discover this Thursday.

## Data Journal — Exit Ticket (5 min, do this now)

Answer in your Data Journal, not here:

1. What dataset or technique did I work with today?
2. What pattern or anomaly surprised me?
3. Who is represented in this data — and who is invisible?
4. What would an ethical data scientist do with this information?

## Submission checklist

- [ ] Data Audit Report filled in
- [ ] Cleaning pipeline runs top-to-bottom with no errors, all `assert` checks pass
- [ ] `climate_cleaned_YYYYMMDD.csv` saved and pushed to your team's GitHub repo
- [ ] 4 charts, each with a finding-based title, labeled axes, and a written interpretation
- [ ] 150-word Data Brief
- [ ] Data Problem Statement — every blank filled, submitted for instructor review
- [ ] Data Journal exit ticket complete

**Notebook submitted to course LMS at the end of session, per syllabus.**

---
# PART B — Week 4: Machine Learning, Classification & Model Comparison + HCD Design Sprint #4
---

# Week 4 — Climate Change Team
## Machine Learning: Classification & Model Comparison (End-to-End)

**Dataset:** Our World in Data — CO2 and Greenhouse Gas Emissions
**HCD Phase:** Prototype — *"Build a testable solution and find out where it fails."*

**Important note before you start:** CO2 emissions data doesn't come with a ready-made yes/no label. In real data science, you often have to **build** the thing you're trying to predict. Today, your instructor has defined it for you:

> **Our prediction target: "High-Emitter Year."** A country-year is labeled **1 (High-Emitter)** if that country's `co2_per_capita` in that year is **above the median** for all country-years in the dataset, and **0 (Not High-Emitter)** if it's at or below the median.

This is a **derived label** — we built it ourselves from a continuous number by picking a cutoff (the median). That is itself an analytical decision, and like every analytical decision, it has consequences you need to be able to explain.

---

### Vocabulary you need before you start

| Term | Plain-English meaning |
|---|---|
| **Feature** | An input the model uses to make its guess (e.g., a country's GDP per person). |
| **Label / target** | The thing you're trying to predict (here: High-Emitter or not). |
| **Train/test split** | You teach the model using one chunk of the data, then quiz it on a *different* chunk it has never seen — this is the only honest way to know if it actually learned something. |
| **Baseline model** | The "dumbest possible guess" — e.g., always guess the most common label. If your fancy model can't beat this, it isn't learning anything useful. |
| **Confusion matrix** | A table of what the model got right and wrong, broken into 4 outcomes (explained below). |
| **Fairness check** | Testing whether a model is equally accurate across different groups — or whether it fails one group more than another. |

### Warm-up discussion (no coding — 3 min)

Recall the COMPAS algorithm from Monday: a recidivism-prediction model that was "accurate on average" but nearly twice as likely to wrongly flag Black defendants as high-risk.

**Discuss with your team:**
1. If we build a model that flags countries as "High-Emitter," who could be harmed by a **false positive** (wrongly flagged) vs. a **false negative** (wrongly NOT flagged)? Think about what a "flag" like this might be used for in the real world — climate financing, trade penalties, media attention.
2. Our derived label uses a **global median** across all countries and all years since the 1800s. What historical unfairness might that bake into the label itself, before the model even trains?

Record your answers in your Data Journal.

## Step 0 — Setup: Load your Week 2 cleaned dataset

**Reminder:** this builds directly on the cleaning work your team did in Week 2. If you don't have your saved CSV handy, the fallback line reloads and re-cleans from the original source.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, recall_score

plt.rcParams["figure.figsize"] = (7, 5)
sns.set_style("whitegrid")

# ---- TRY to load your Week 2 cleaned file first; fall back to a fresh clean if not found ----
import os
CLEANED_FILE = "climate_cleaned_YYYYMMDD.csv"   # <-- replace with YOUR team's actual saved filename

if os.path.exists(CLEANED_FILE):
    df = pd.read_csv(CLEANED_FILE)
    print("Loaded your Week 2 cleaned file:", df.shape)
else:
    print("Cleaned file not found -- reloading and re-cleaning from source (Week 2 steps, condensed).")
    RAW_URL = "https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv"
    raw = pd.read_csv(RAW_URL)
    core_cols = ["country", "year", "iso_code", "population", "gdp", "co2", "co2_per_capita",
                 "co2_growth_prct", "coal_co2", "oil_co2", "gas_co2", "cement_co2",
                 "primary_energy_consumption", "energy_per_capita", "methane", "nitrous_oxide",
                 "total_ghg", "temperature_change_from_co2", "temperature_change_from_ghg"]
    df = raw[core_cols].copy()
    df = df[df["iso_code"].notnull()].copy()
    df = df.dropna(subset=["co2", "co2_per_capita"]).copy()
    df[["coal_co2","oil_co2","gas_co2","cement_co2"]] = df[["coal_co2","oil_co2","gas_co2","cement_co2"]].fillna(0)
    print("Re-cleaned shape:", df.shape)

df.head()

"""## Step 1 — Define the Prediction Problem

We build the "High-Emitter Year" label from `co2_per_capita` using the **median** as the cutoff.

**Concept check:** why the *median* and not the *mean*? The mean is dragged upward by a handful of extremely high-emitting countries (outliers). The median is the true "middle" value — half of all country-years are above it, half below. That makes for a more balanced label.

"""

median_value = df["co2_per_capita"].median()
print(f"Median CO2 per capita across the dataset: {median_value:.2f} tonnes")

df["high_emitter"] = (df["co2_per_capita"] > median_value).astype(int)

print("\nClass balance (this should be close to 50/50, since we used the median):")
print(df["high_emitter"].value_counts(normalize=True).round(3))

"""> **Data Journal prompt:** A country that was a "High-Emitter" in 1950 might not be one today, and vice versa. Pick one real country from the data and check: has its `high_emitter` label changed over time? What does that tell you about treating this as a fixed category versus something that changes?

"""

# Checking whether one real country's high_emitter label has changed over time
example = df[df["country"] == "South Korea"].sort_values("year")
print(example[["year", "co2_per_capita", "high_emitter"]].iloc[[0, -1]])

"""**Answer:** Yes — South Korea's `high_emitter` label changes over time. In its earliest recorded year, its `co2_per_capita` was essentially 0 and it was labeled `0` (Not High-Emitter). By the most recent year, its per-capita emissions had risen to over 11 tonnes/person and it's labeled `1` (High-Emitter). This shows that treating "High-Emitter" as a fixed, permanent category would be misleading — it's really a snapshot of a country's *current* energy profile, which can shift dramatically as a country industrializes. A model (or a policy) that treats this as a fixed trait rather than a moving target risks judging a country by where it used to be, not where it is now.

## Step 2 — Feature Engineering

**Critical concept — data leakage:** We CANNOT use `coal_co2`, `oil_co2`, `gas_co2`, or `total_ghg` as features. Why? Because those numbers are literally the ingredients that `co2_per_capita` is built from — using them would be like "predicting" whether someone is tall using their height in a different unit. The model would look impressively accurate and teach you nothing.

**Instead, we'll use features that are *related* to emissions but not derived directly from them:**
- `gdp_per_capita` (created below) — a country's wealth per person
- `population` — country size
- `primary_energy_consumption` — total energy use (related to, but not identical to, emissions)
- `energy_per_capita` — energy use per person
- `methane`, `nitrous_oxide` — different greenhouse gases (not CO2 itself)
- `year` — captures broad historical trends

### Machine Learning — Deep Dive: 5 Key Variables

We deliberately trained our models on exactly **5 features**, each chosen to avoid data leakage (see the concept note below) while still capturing a country's economic and energy profile:

| # | Variable | What it captures | Why it's a fair (non-leaky) predictor |
|---|----------|-------------------|----------------------------------------|
| 1 | `gdp_per_capita` | Economic output per person | Wealth influences energy demand but isn't a direct restatement of emissions. |
| 2 | `population` | Country size | Tests whether sheer headcount predicts high-emitter status (our Week 2 finding says mostly no). |
| 3 | `energy_per_capita` | Energy consumption per person | A country's energy appetite is a plausible *cause* of emissions, not a re-labeling of them. |
| 4 | `methane` | Total methane emissions | A different greenhouse gas — correlated with overall industrial/agricultural activity, not derived from `co2` itself. |
| 5 | `nitrous_oxide` | Total nitrous oxide emissions | Same logic as methane — a related but independent emissions signal. |

We explicitly **excluded** `coal_co2`, `oil_co2`, `gas_co2`, and `total_ghg` as features (see below) because they are literally the components `co2_per_capita` is built from.
"""

# Create gdp_per_capita
df["gdp_per_capita"] = df["gdp"] / df["population"]

# ---- 5-VARIABLE feature set (per assignment requirement) ----
# gdp_per_capita, population, energy_per_capita, methane, nitrous_oxide
feature_cols = ["gdp_per_capita", "population", "energy_per_capita", "methane", "nitrous_oxide"]

# HINT LADDER if you want to add/remove features:
#  Nudge: does adding a feature make conceptual sense, or could it be leakage (derived from co2)?
#  Syntax: just add/remove the column name (string) from feature_cols above.
#  Bridge: after changing features, re-run every cell below this one in order.

# Drop rows missing any feature we need
model_df = df.dropna(subset=feature_cols + ["high_emitter"]).copy()
print("Rows available for modeling:", len(model_df))
print("Rows dropped due to missing features:", len(df) - len(model_df))

model_df[feature_cols].describe()

"""> **Written justification (fill in):** We dropped **15,208** rows because they were missing at least one of our chosen features (mostly `energy_per_capita`, which has much sparser historical coverage than `co2` itself). This likely affects **smaller and lower-income countries, and earlier decades in general** more than others, since energy-consumption and GDP reporting infrastructure has historically been strongest in large, wealthy, industrialized nations — which means our model's results should be read as most reliable for well-documented countries and less certain for the countries with the thinnest historical records.

## Step 3 — Train/Test Split

**Concept check:** we train the model on 80% of the data and test it on the other 20% — data the model has **never seen**. If we tested it on data it already memorized, we'd have no idea if it actually learned a real pattern or just memorized answers.

**Function hint:** `train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)` — `stratify=y` makes sure both the train and test sets have a similar High-Emitter/Not split, so the test is fair.
"""

X = model_df[feature_cols]
y = model_df["high_emitter"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Training rows:", len(X_train), "| Test rows:", len(X_test))
print("\nClass balance in training set:")
print(y_train.value_counts(normalize=True).round(3))
print("\nClass balance in test set:")
print(y_test.value_counts(normalize=True).round(3))

"""### Standardize the features

**Concept check:** some models (like k-NN) measure "distance" between data points. If `population` is in the hundreds of millions and `gdp_per_capita` is in the thousands, population will completely dominate the distance calculation just because its numbers are bigger — not because it's actually more important. Standardizing rescales every feature to the same range so each one gets a fair vote.

"""

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Note: we fit the scaler ONLY on training data, then apply it to test data.
# This prevents the test set from "leaking" information into training.

"""## Step 4 — Establish a Baseline (the "dumbest possible guess")

Before we train any real model, we need a floor to beat. `DummyClassifier(strategy="most_frequent")` always predicts whatever label is most common — it doesn't look at the features at all. If our real models can't beat this, they aren't learning anything.

"""

baseline = DummyClassifier(strategy="most_frequent")
baseline.fit(X_train_scaled, y_train)
baseline_pred = baseline.predict(X_test_scaled)
baseline_acc = accuracy_score(y_test, baseline_pred)

print(f"Baseline accuracy (always guess the most common class): {baseline_acc:.3f}")
print("Any real model MUST beat this number, or it has learned nothing useful.")

"""## Step 5 — Train and Compare Multiple Algorithms

We'll train **four** classifiers on the exact same data and compare them fairly. Each has a different way of "thinking":

- **Logistic Regression** — finds a smooth mathematical boundary between the two classes based on weighted combinations of features. Fast, and easy to explain ("more energy_per_capita increases the odds of High-Emitter").
- **k-Nearest Neighbors (k-NN)** — classifies a country-year by looking at the *k* most similar rows (its "neighbors") and taking a majority vote.
- **Decision Tree** — asks a sequence of yes/no questions ("is `energy_per_capita` above X? then is `gdp_per_capita` above Y?") until it reaches an answer. Easy to visualize as a flowchart.
- **Random Forest** — trains *many* decision trees on random subsets of the data and lets them vote together. Usually more accurate and less prone to memorizing quirks than a single tree.

**Baseline hyperparameters are given below. Your job: tweak at least ONE hyperparameter per model and observe what changes.**

"""

# BASELINE MODELS -- read the comments, then tweak the marked hyperparameters

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

models = {
    "Logistic Regression": LogisticRegression(random_state=42, max_iter=1000),

    # HINT: n_neighbors (k) controls how many "neighbors" vote.
    #   Small k (e.g. 3) -> very sensitive to noise / individual points ("overfit")
    #   Large k (e.g. 50) -> smoother, but may blur real distinctions ("underfit")
    #   TWEAK: try k=3, k=15, k=50 and compare accuracy below.
    "k-Nearest Neighbors": KNeighborsClassifier(n_neighbors=15),

    # HINT: max_depth controls how many yes/no questions the tree can ask.
    #   Shallow tree (depth=2) -> simple, explainable, may miss real patterns
    #   Deep tree (depth=None) -> can memorize the training data ("overfit") and fail on new data
    #   TWEAK: try max_depth=2, max_depth=6, max_depth=None and compare.
    "Decision Tree": DecisionTreeClassifier(max_depth=4, random_state=42),

    # HINT: n_estimators is how many trees vote together. More trees = more stable,
    #   but slower. TWEAK: try n_estimators=10 vs n_estimators=200.
    "Random Forest": RandomForestClassifier(n_estimators=100, max_depth=6, random_state=42),
}

results = {}
predictions = {}

for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    pred = model.predict(X_test_scaled)
    predictions[name] = pred
    results[name] = {
        "Accuracy": accuracy_score(y_test, pred),
        "Precision": precision_score(y_test, pred),
        "Recall": recall_score(y_test, pred),
        "F1 Score": f1_score(y_test, pred)
    }

    print(
        f"{name:25s} | "
        f"Accuracy = {results[name]['Accuracy']:.3f} | "
        f"Precision = {results[name]['Precision']:.3f} | "
        f"Recall = {results[name]['Recall']:.3f} | "
        f"F1 = {results[name]['F1 Score']:.3f}"
    )

# comparing everything in a new table
results_df = (
    pd.DataFrame(results)
    .T
    .sort_values(by="F1 Score", ascending=False)
)

results_df.style \
    .background_gradient(
        cmap="Greens",
        subset=["Accuracy", "Precision", "Recall", "F1 Score"]
    ) \
    .format("{:.3f}")

"""## Step 6 — Evaluate & Compare in Detail

**Concept check — the Confusion Matrix:**

| | Predicted: Not High-Emitter | Predicted: High-Emitter |
|---|---|---|
| **Actually: Not High-Emitter** | True Negative (correct) | False Positive (wrongly flagged) |
| **Actually: High-Emitter** | False Negative (missed it) | True Positive (correct) |

- **Precision** = of everything the model flagged as High-Emitter, how much was actually correct?
- **Recall** = of everything that WAS actually High-Emitter, how much did the model catch?

Which one matters more depends on the real-world use of the flag — think back to your warm-up discussion.

"""

for name, pred in predictions.items():
    print(f"===== {name} =====")
    print(classification_report(y_test, pred, target_names=["Not High-Emitter", "High-Emitter"]))
    print()

"""### Statistical Significance Check: Is Random Forest *Actually* Better Than Logistic Regression?

Random Forest scored higher on every metric, but with a finite test set, is that gap statistically meaningful or could it be luck of the draw on this particular train/test split? We check this with **McNemar's test**, which is designed exactly for this situation: comparing two classifiers on the *same* test set by looking only at the cases where they disagree.

"""

from scipy.stats import binomtest

# McNemar's test compares two classifiers on the SAME test examples, using only the
# "discordant pairs" -- cases where one model got it right and the other got it wrong.
lr_pred = predictions["Logistic Regression"]
rf_pred = predictions["Random Forest"]
y_test_arr = y_test.values

lr_correct = (lr_pred == y_test_arr)
rf_correct = (rf_pred == y_test_arr)

lr_only_correct = int(np.sum(lr_correct & ~rf_correct))   # LR right, RF wrong
rf_only_correct = int(np.sum(~lr_correct & rf_correct))   # RF right, LR wrong
n_discordant = lr_only_correct + rf_only_correct

print(f"Cases where only Logistic Regression was correct: {lr_only_correct}")
print(f"Cases where only Random Forest was correct:       {rf_only_correct}")
print(f"Total discordant cases: {n_discordant}")

# Under the null hypothesis (both models equally good), each discordant case is a
# coin flip as to which model gets it right -- so we test against a 50/50 binomial.
mcnemar_result = binomtest(min(lr_only_correct, rf_only_correct), n_discordant, 0.5, alternative="two-sided")
print(f"\nMcNemar's exact test p-value: {mcnemar_result.pvalue:.2e}")

if mcnemar_result.pvalue < 0.05:
    print("p < 0.05 -- Random Forest's advantage over Logistic Regression is statistically significant.")
else:
    print("p >= 0.05 -- we cannot say the two models perform significantly differently.")

"""**Result:** Of the 51 test cases where the two models disagreed, Random Forest was right 44 times and Logistic Regression was right only 7 times (McNemar's exact p ≈ 1.2 × 10⁻⁷). This is a statistically significant difference — Random Forest's edge over Logistic Regression isn't just noise from this particular train/test split, it reflects a real, repeatable advantage on this task.

> **Written comparison (fill in):** The model with the highest accuracy is **Random Forest** (0.977). The model with the highest recall for High-Emitter is also **Random Forest** (0.979). These are the **same** model *(circle one)*. In this run they happen to agree, but that isn't guaranteed in general — a model can be "more accurate overall" while being worse at catching a specific class when the classes are imbalanced. For example, a model that just guesses "not High-Emitter" every time for a rare class could still score high on accuracy while having zero recall for the class you actually care about; accuracy rewards getting the *majority* of predictions right, while recall specifically asks "of everyone who truly belongs in this class, how many did we find?"

## Step 7 — Fairness Check

This dataset doesn't include a demographic column like race or gender. But it DOES let us check something equally important for a global climate model: **does the model perform equally well for rich countries versus poor countries?** If a "High-Emitter" flag is going to influence real decisions (climate financing, trade policy, media narratives), a model that's much less accurate for low-income countries would be a serious problem — it could unfairly blame or unfairly excuse specific groups of nations based on model error, not reality.

**We'll split countries into income tiers using `gdp_per_capita`**, a proxy already available in our features.

**Note this is a proxy, not a perfect measure** — a country's income tier changes over time, and per-capita GDP is an imperfect stand-in for a country's actual development context. Say so in your writeup.
"""

# Recover the test set's gdp_per_capita (dropped when we scaled to a plain array)
test_gdp_pc = X_test["gdp_per_capita"].reset_index(drop=True)

# Split into income tiers using quartiles (roughly equal-sized groups)
income_tier = pd.qcut(test_gdp_pc, q=3, labels=["Low income tier", "Middle income tier", "High income tier"])

y_test_reset = y_test.reset_index(drop=True)

# Use your best-performing model from Step 6 -- CHANGE this variable name to match your top model
best_model_name = "Random Forest"   # <-- TWEAK: set this to whichever model had the best results
best_pred = pd.Series(predictions[best_model_name]).reset_index(drop=True)

fairness_df = pd.DataFrame({
    "income_tier": income_tier,
    "actual": y_test_reset,
    "predicted": best_pred,
})

print(f"Fairness check for: {best_model_name}\n")
for tier in ["Low income tier", "Middle income tier", "High income tier"]:
    subset = fairness_df[fairness_df["income_tier"] == tier]
    acc = accuracy_score(subset["actual"], subset["predicted"])
    rec = recall_score(subset["actual"], subset["predicted"], pos_label=1, zero_division=0)
    print(f"{tier:20s} | n={len(subset):4d} | accuracy = {acc:.3f} | recall(High-Emitter) = {rec:.3f}")

"""> **Fairness write-up (fill in):**
>

Is the performance relatively the same across the income tiers or is the model worse at catching some classes than others? No-the model is not equally fair. Accuracy appears to be relatively same across the tiers (0.965 / 0.967 / 1.000), but the classes are not evenly represented by income level so accuracy is misleading. The Recall in the High-Emitter class provides a better picture of what is happening: 76.7% in the low income tier, 98.3% in the middle tier, and 100% in the high income tier. The model is definitely doing worse at catching the true High-Emitters when they're associated with poorer countries.
If there IS a gap what is one real world consequence that this could have if this model were used to make actual policy/financing decisions? For a low income country that is indeed moving into the "High-Emitter" level-presumably as it is rapidly industrializing-it would likely be missed by the model. The countries missed would be excluded from emissions reducing grants/assistance programs or judged differently to rich countries that the model easily identifies which could only reinforce existing inequalities.
What is ONE thing you could try to reduce that gap? We could try oversampling or undersampling to make each tier have roughly same number of rows (current is unlikely to represent income tiers equally) or at a minimum create an income-tier aware step in all future model development so the gap does not go unnoticed until after the model has already been developed and deployed.

## Step 8 — Recommendation

Write 3 sentences, following this pattern from the syllabus:

> "I recommend **[model]** for this application because **[metric]** is most important, given that a false negative here means **[human consequence]** and a false positive means **[human consequence]**."

Fill in your own answer below:

> **Our recommendation:** I recommend the Random Forest classifier for this application because recall on the High-Emitter class is most important, given that a false negative here means a genuinely high-emitting country gets excluded from climate-accountability reporting or emissions-reduction outreach it should have received, while a false positive means a country gets extra scrutiny or reporting requirements it didn't strictly need. Random Forest had both the highest overall F1 score (0.983) and the highest recall (0.979) of the four models we tested, clearing the 66.8% dummy-baseline accuracy by over 30 points. That said, our fairness check in Step 7 shows this same model catches only 76.7% of true High-Emitters in the lowest income tier versus 100% in the highest tier, so we would not deploy it as-is for a real financing decision without addressing that gap first.

## HCD Design Sprint #4 — Prototype: Assemble Your Capstone Prototype

Your team's Capstone prototype must now include, at minimum:

1. A cleaned dataset with a documented cleaning log *(from Week 2)*
2. 3 final visualizations supporting your central finding *(from Week 2)*
3. A regression or classification analysis with fully interpreted results *(Week 3 regression + this notebook's classification)*
4. A draft policy recommendation, in this exact format:

> "Based on our data analysis, we recommend that **[institution]** take the following action, because our evidence shows **[specific finding]** implies **[specific consequence]** for **[population]** if unaddressed."

Fill in your team's draft below:

> **Our policy recommendation:** Based on our data analysis, we recommend that national climate-finance bodies (e.g., the UNFCCC Green Climate Fund) weight eligibility partly by current per-capita emissions trend rather than historical totals alone, because our evidence shows that our Random Forest model can correctly flag rising ‘High-Emitter’ status with 97.8% accuracy overall, but is measurably worse at catching true positives in the lowest income tier (76.7% recall vs. 100% in the highest tier) - implying that fast-industrializing, lower-income countries crossing the high-emissions threshold are the ones most likely to be missed for targeted energy-transition funding if unaddressed.”

**Peer review (trade with another team):**
Strongest evidence: The fairness check is the strongest part of this prototype. Showing a quantified recall gap (76.7% vs. 100%) across income tiers is far more convincing than just claiming a model "seems fair."

Biggest gap between the data and the recommendation: The model was trained on national-level features (GDP, population, energy use), not on the political or infrastructural reasons a country crosses the emissions threshold. This means the recommendation assumes the model's flag is a good proxy for "needs support," which isn't actually proven here.

One more analysis that would strengthen this: Testing whether the low-income-tier recall gap persists after re-balancing the training data by income tier, to see if it's a data-volume problem rather than a genuine harder-to-predict pattern.

## Data Journal — Exit Ticket

1. What does it mean for an algorithm to be fair? Is fairness the same as accuracy?
No, they aren’t the same and it is one of the more counter-intuitive concepts in ML ethics in honestly. It is quite possible to have a model with a high overall accuracy but where one subgroup is far more misrepresented than another (95% accurate overall, but 70% accurate for just one subgroup). Also, there are multiple competing math-based definitions of fairness (e.g. Equal rates of false positive across different groups, equal accuracy across different groups, equal representation across the outcome), and mathematically speaking it is proven to not be possible to satisfy all of them simultaneously. Therefore “fair” isn’t some defined target state but is the choice about which specific trade-off is most important for whatever specific decision you are making.
2. Who should be allowed to define what counts as a fair prediction for a model like this — the model developer, the company, the government, or the countries the model affects?
- The model developers understand the technical trade-offs best, but might not be accountable for future negative outcomes.
- The company is the group who has to answer to the law and the public for reputation/legal risk, but have incentive structures based on profit which do not necessarily align with “fair.”
- The government can institute enforceble guidelines and provides some form of democratic accountability, but is generally much slower to innovate than engineers and less technically adept.
- The “affected” nations/communities of course bear the consequences of the models and their decisions, but are almost never included in conversations like these ( especially as in these case the models involve international data sets and issues).

3. If you were a policymaker and someone showed you this model's results, what is the FIRST question you would ask before trusting it?
Candidates include “what data was used to train this model, and whose actions/emissions is this model under or over-weighted by?” Or “what definition of fair is used here and who decided on it?” For this specific notebook- where you are using national CO2 emissions data - a very strong answer could be “does this model's framing of CO2 emissions as per-capita reflect an analysis of why different nations have different per-capita emissions (such as histories of colonization/industrialization), or does it assume that all nations reached current emission levels in similar fashions?"

## Submission checklist

- [ ] Target variable (`high_emitter`) defined with justification for the median cutoff
- [ ] Feature set chosen with leakage explicitly avoided and justified
- [ ] Train/test split performed with `stratify=y`
- [ ] Baseline (dummy) accuracy recorded as the floor to beat
- [ ] All 4 models trained; at least one hyperparameter tweaked per model
- [ ] Confusion matrices and classification reports compared across all models
- [ ] Fairness check completed across income tiers, with a written response
- [ ] Model recommendation written in the required sentence format
- [ ] HCD Prototype assembled and peer-reviewed
- [ ] Data Journal exit ticket complete
- [ ] Results CSV pushed to GitHub

**Notebook submitted to course LMS / GitHub, per syllabus.**

---
# PART C — Deep Learning: 1-Variable Neural Network
---

## Why a Neural Network, and Why Just 1 Variable?

Everything in Part B used "classical" machine learning models (logistic regression, k-NN, decision trees, random forest). A **neural network** is a different kind of model: instead of one mathematical rule or one tree of yes/no questions, it's built from layers of small computing units ("neurons") that each learn a tiny piece of a pattern, then combine those pieces together. This is what "deep" in *deep learning* refers to — multiple stacked layers, each transforming the signal a bit further.

We deliberately use **1 input variable** here — `gdp_per_capita` — to keep the network simple enough to reason about and to see clearly how much predictive power a neural network can squeeze out of a *single* number, compared to the 5-variable Random Forest from Part B.
"""

# ---- Deep Learning setup ----
# We use scikit-learn's MLPClassifier here (a Multi-Layer Perceptron -- a genuine, if small,
# neural network) since this environment doesn't have TensorFlow/PyTorch installed. MLPClassifier
# trains the same way: forward pass -> loss calculation -> backpropagation -> weight update,
# repeated over many epochs.

from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Reuse the same model_df and high_emitter target from Part B, but with just 1 feature this time
X1 = model_df[["gdp_per_capita"]]   # <-- the ONE variable this section is about
y1 = model_df["high_emitter"]

X1_train, X1_test, y1_train, y1_test = train_test_split(
    X1, y1, test_size=0.2, random_state=42, stratify=y1
)

# Neural networks are sensitive to input scale, just like k-NN -- always standardize first
scaler1 = StandardScaler()
X1_train_scaled = scaler1.fit_transform(X1_train)
X1_test_scaled = scaler1.transform(X1_test)

print("Training rows:", len(X1_train), "| Test rows:", len(X1_test))

# ---- Build and train the network ----
# hidden_layer_sizes=(16, 8) means: 1 input -> hidden layer of 16 neurons -> hidden layer of
# 8 neurons -> 1 output neuron (High-Emitter probability). Each layer learns a progressively
# more abstract transformation of the single gdp_per_capita signal.
mlp = MLPClassifier(
    hidden_layer_sizes=(16, 8),
    activation="relu",       # standard non-linearity: lets the network learn curves, not just straight lines
    max_iter=500,            # maximum number of training epochs
    random_state=42
)

mlp.fit(X1_train_scaled, y1_train)
mlp_pred = mlp.predict(X1_test_scaled)

print("1-variable Neural Network results (predicting High-Emitter from gdp_per_capita alone):")
print(f"  Accuracy:  {accuracy_score(y1_test, mlp_pred):.3f}")
print(f"  Precision: {precision_score(y1_test, mlp_pred):.3f}")
print(f"  Recall:    {recall_score(y1_test, mlp_pred):.3f}")
print(f"  F1 Score:  {f1_score(y1_test, mlp_pred):.3f}")
print(f"\nTraining ran for {len(mlp.loss_curve_)} epochs before converging.")

# ---- Visualize training: the loss curve ----
# "Loss" measures how wrong the network's predictions are during training. A network that's
# actually learning should show loss dropping quickly at first, then leveling off as it
# converges on a good set of weights.
plt.figure()
plt.plot(mlp.loss_curve_, linewidth=2)
plt.xlabel("Training epoch")
plt.ylabel("Training loss")
plt.title("Neural Network Loss Drops Sharply, Then Levels Off -- a Sign of Convergence")
plt.show()

"""# Deep Learning - Results

Even with only 1 feature (gdppercapita) provided, our neural network achieved 92.4% accuracy, 94.9% precision, and 93.6% recall for our High-Emitter task -- trouncing Part B's 66.8% dummy baseline accuracy with 1/5th the input data (1 feature vs 5).

Part B Comparison: Our 5-feature Random Forest is still more accurate (97.7% vs 92.4% accuracy), which is expected, given that it benefits from 4 additional inputs (our population, energypercapita, methane, and nitrousoxide variables). But that difference is smaller than it might appear at first:  gdpper_capita itself is remarkably predictive, which reinforces our Part A observation of strong correlation between gdp and total emissions (r 0.92). This serves as an important confirmation of our analysis; had the 1-feature network achieved as high an accuracy as the 5-feature one, that would have indicated the other 4 features weren't adding substantial non-redundant information; this meaningful drop validates that the extra features provide valuable insights beyond just per-capita GDP.

Training: "The Shape of a Neural Network": As the loss plot shows, our network "learned" rapidly; the loss function plateaus quickly after the initial ~20 epochs -- a sign of successful convergence rather than the flat line of random guesses or the steady decline characteristic of over-fitting.

"""